### ISSUE TITLE
无法添加交易

### ISSUE THREAD

**Issue by dofine** [kaaass/beancount_bot_costflow#1]
尝试运行：

`node costflow-parser.js --config costflow.json --json 'c2f 20'` 时 提示

```
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

版本信息：
node: 12.22.5

配置文件（已在 costflow playground 验证正常）
```
{
    "mode": "beancount",
    "currency": "CNY",
    "account": {
        "cmb": "Assets:Bank:CN:CMB",
        "food": "Expenses:Food:Meals"
    },
    "formula": {
        "c2f": "{{ pre }} cmb > food"
    },
    "defaultAccount": "Assets:US:BofA:Checking",
    "alphavantage": null,
    "indent": 2,
    "lineLength": 50,
    "insertTime": "metadata"
}
```

**Comment by dofine** [comment]
好像是 Debian 默认的 nodejs 版本太低了。。升级之后正常~

**Comment by kaaass** [comment]
感谢报告，我自己本地的 Node 版本都 >= 14，所以之前都没有意识到这个问题
